package exp.rusan.musicplayer.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import exp.rusan.musicplayer.SongBean;

import exp.rusan.musicplayer.dao.SongBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songBeanDaoConfig;

    private final SongBeanDao songBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songBeanDaoConfig = daoConfigMap.get(SongBeanDao.class).clone();
        songBeanDaoConfig.initIdentityScope(type);

        songBeanDao = new SongBeanDao(songBeanDaoConfig, this);

        registerDao(SongBean.class, songBeanDao);
    }
    
    public void clear() {
        songBeanDaoConfig.clearIdentityScope();
    }

    public SongBeanDao getSongBeanDao() {
        return songBeanDao;
    }

}
