package exp.rusan.musicplayer.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import exp.rusan.musicplayer.TrackStore.Track;

import exp.rusan.musicplayer.dao.TrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackDaoConfig;

    private final TrackDao trackDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        trackDao = new TrackDao(trackDaoConfig, this);

        registerDao(Track.class, trackDao);
    }
    
    public void clear() {
        trackDaoConfig.clearIdentityScope();
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

}
